[features]
seeds = false

[programs.localnet]
vyper_core = "mb9NrZKiC3ZYUutgGhXwwkAL6Jkvmu5WLDbxWRZ8L9U"
rate_mock = "FB7HErqohbgaVV21BRiiMTuiBpeUYT8Yw7Z6EdEL7FAG"
rate_switchboard = "B97awSfAvfqicTnTpDbRLq8JauxS9UuvTdwVyx3nDxTF"
redeem_logic_lending = "Gc2ZKNuCpdNKhAzEGS2G9rBSiz4z8MULuC3M3t8EqdWA"
redeem_logic_vanilla_option="8fSeRtFseNrjdf8quE2YELhuzLkHV7WEGRPA9Jz8xEVe"
redeem_logic_lending_fee = "3mq416it8YJsd5DKNuWeoCCAH8GYJfpuefHSNkSP6LyS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# BTC USD Switchboard: https://switchboard.xyz/explorer/3/8SXvChNYFhRq4EZuZvnhjrB3jJRQCv4k3P4W6hesH3Ee
[[test.validator.clone]]
address = "8SXvChNYFhRq4EZuZvnhjrB3jJRQCv4k3P4W6hesH3Ee"

# USDC USD Switchboard: https://switchboard.xyz/explorer/3/BjUgj6YCnFBZ49wF54ddBVA9qu8TeqkFtkbqmZcee8uW
[[test.validator.clone]]
address = "BjUgj6YCnFBZ49wF54ddBVA9qu8TeqkFtkbqmZcee8uW"

# XTZ USD Switchboard: https://switchboard.xyz/explorer/3/F11LACseaLXuRaPSvnD6w15vSPHtx73YaGZv9293rQQm
[[test.validator.clone]]
address = "F11LACseaLXuRaPSvnD6w15vSPHtx73YaGZv9293rQQm"