[package]
name = "proxy-interface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "proxy_interface"

[dependencies]
anchor-lang = { version = "0.19.0" }
anchor-spl = "0.19.0"

