[package]
name = "proxy-lending-interface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "proxy_lending_interface"

[dependencies]
anchor-lang = "0.18.2"
anchor-spl = "0.18.2"
